export default {
    locale: 'en-us',
    agent:{
        "title": "Lambda Platform",
        "subtitle": "Lambda Platform",
        "login": "Login",
        "forgot": "Forgot password?",
        "remember": "Remember me",
        "loginTitle": "Login to system",
        "username": "Username",
        "email": "e-mail",
        "password": "Password",
        "loginSuccess": "Successfully logged in. Please wait for a moment!",
        "loginError": "Sorry, an error occurred while logging in!!",
        "emailRequired": "Please enter an email address",
        "emailSendError": "An error occurred while sending the email",
        "forgotDescription": "Enter your email address and reset your password",
        "sendPasswordResetCode": "Receive password reset code by email",
        "passwordConfirm": "Password verification",
        "userNotFound": "User not found !!!",
        "codeSentError": "An error occurred while sending the password update code!",
        "passwordReset": "Password reset",
        "passwordResetCode": "Password reset code",
        "passwordResetCodeSent": "Password update code sent successfully !",
        "passwordResetCodeRequired": "Password change code not included !!!",
        "passwordResetSuccess": "Password successfully updated !",
        "passwordConfirmError": "Password authentication did not match !!!",
        "passwordResetCodeIncorrect": "The password recovery code is incorrect !!!",
        "passwordResetCodeTimeout": "Password recovery code has expired !!!",
        "noReply": "This email was sent automatically, so there is no need to reply."
    },
    puzzle:{
        db:"Database",
        userAndUserGroup:"User, User group",
        users:"User",
        userGroupsPermission:"User groups, Permissions",
    },
    common:{
        logout:"Logout",
    }
}
