export default {
    locale: 'en-us',
    user:{
        "title": "Lambda Platform",
        "subtitle": "Lambda Platform",
        "login": "Login",
        "forgot": "Forgot password?",
        "remember": "Remember me",
        "loginTitle": "Login to system",
        "username": "Username",
        "email": "e-mail",
        "password": "Password",
        "loginSuccess": "Successfully logged in. Please wait for a moment!",
        "loginError": "Sorry, an error occurred while logging in!!",
        "emailRequired": "Please enter an email address",
        "emailSendError": "An error occurred while sending the email",
        "forgotDescription": "Enter your email address and reset your password",
        "sendPasswordResetCode": "Receive password reset code by email",
        "passwordConfirm": "Password verification",
        "userNotFound": "User not found !!!",
        "codeSentError": "An error occurred while sending the password update code!",
        "passwordReset": "Password reset",
        "passwordResetCode": "Password reset code",
        "passwordResetCodeSent": "Password update code sent successfully !",
        "passwordResetCodeRequired": "Password change code not included !!!",
        "passwordResetSuccess": "Password successfully updated !",
        "passwordConfirmError": "Password authentication did not match !!!",
        "passwordResetCodeIncorrect": "The password recovery code is incorrect !!!",
        "passwordResetCodeTimeout": "Password recovery code has expired !!!",
        "noReply": "This email was sent automatically, so there is no need to reply.",
        "databaseview": "Database, view",
        "dataBase": "database",
        "view": "VIEW",
        "add": "add",
        "characteristics": "Characteristics",
        "basic": "Basic",
        "column": "column",
        "name": "name",
        "optional": "optional",
        "filter": "filter",
        "data": "data",
        "save": "save",
        "tableList"	: "table list",
        "aggregation": "Aggregation",
        "sort": "sort",
        "use": "use",
        "grouping": "grouping",
        "type": "type",
        "alias": "alias",
        "dataProcessing": "Data processing",
        "select": "select",
        "pleaseEnterSearchValue": "Please enter a search value",
        "user": "User",
        "users": "Users",
        "totalEmployees": "Total employees",
        "deleted": "Deleted",
        "searchForInformation": "Search for information",
        "addUser": "Add a user",
        "noData": "No matching data",
        "page": "page",
        "shows": "shows",
        "categorySearch": "category search",
        "image": "image",
        "lastName": "last name",
        "firstName": "first name",
        "registrationNumber": "Registration number",
        "dateOfBirth": "Date of birth",
        "gender": "gender",
        "men": "Men",
        "women": "Women",
        "phone": "phone",
        "fillInTheNewOne": "Fill in the new one",
        "permission": "Permission",
        "loginName": "Login name",
        "confirmPassword": "Confirm password",
        "personalInformation": "Personal information",
        "changePassword": "Change password",
        "settings": "Settings",
        "logOut": "Log out",
        "pleaseSelectRole": "Please select a role",
        "administraationRightsManagment": "Administration rights management",
        "additional": "ADDITIONAL",
        "dataSource": "Data source",
        "chart": "Chart",
        "userList": "User list",
        "import": "Import",
        "register": "Register",
        "confirm": "Confirm",
        "menuSelection": "Menu selection",
        "noMatchingData": "No matching data",
        "nickName": "Nickname",
        "note": "Note",
        "pleaseEnterVisibleName": "Please enter a visible name",
        "firstNameandLastName": "First name & last name",
        "mobile": "Mobile",
        "createdDate": "created date",
        "registrationConfirmed": "REGISTRATION CONFIRMED",
        "registrationIsNotConfirmed": "REGISTRATION IS NOT CONFIRMED",
        "success": "success",
        "systemUpdate": "System update",
        "sendDataStructure": "Send data structure",
        "pleaseReEnterYourPassword": "Please re-enter your password",
        "theValueIsRegistered": "The value is registered",
        "possibleTableView": 'Possible "table" and "view"',
        "table": "Table",
        "ascending": "Ascending",
        "descending": "descending",
        "dateAdded": "Date added",
        "byLoginName": "by login name",
        "inPage": "in page",
        "show": "Show",
        "outOf": "total",
        "fromUsers": "from users",
        "showing": "showing",
        "noInfo": "No information ",
        "ruconfinfo": "Are you confident in retrieving employee information?",
        "ruconfinfoDelete": "Are you sure you want to delete employee information completely?",
        "created": "Created",
        "userDeleted": "User deleted",
        "_logout":"Logout",
        "_cancel":"Cancel",
        "listOfDeletedUsers": "List of deleted users",
        "by": "by",
        "no": "no",
        "yes":"yes",
        "completeDestruction": "Complete destruction",
        "recovery": "Recovey",
        "errorOccWhileDeleting": "An error occurred while deleting",
        "userInformationRestored": "User information restored",
        "errorOccurredWhileRetrievingData": "An error occurred while retrieving the data",
        "total": "total",
        "edit":"Edit",

    },
    adminModule:{
        "db":"Database",
        "usersAndUserGroups":"User, User group",
        "users":"Users",
        "userGroupsPermission":"User groups, Permissions",
        "sendDBSchema":"Send Database schema",
        "applications":"Applications",
        "additions":"Additions",
        "logistics":"Logistics",
        "AddColumn":"Add a column",
        "systemUpdate":"System update",
        "graphic":"Graphic",
        "column":"Column",
        "dataType":"Data type",
        "form":"Form",
        "table":"Table",
        "original_preparation": "Original preparation",
    },
    graphql:{
        "graphqlManagement":"Graphql management",
        "table":"Table",
        "selectTable":"Select a table",
        "name": "Name",
        "idField":"ID field",
        "hideFields":"Hide fields",
        "permissionActions":"Permission actions",
        "add":"Add",
        "edit":"Edit",
        "delete":"Delete",
        "save": "Save",
        "accessAndAccessRights":"Access and access rights",
        "nevtersenHundHaruulah":"Show it to anyone who has logged in.",
        "accessRights":"Access rights",
        "allUsersCanSee":"All users can see it if they are not authorized",
        "subTables":"Sub-tables",
        "subTable":"Sub-table",
        "connectionField":"Connection field",
        "tableList":"table list",
        "viewList": "View list",

    },
    components:{
        "add": "Add",
        "pleaseEnterSearchValue": "Please enter a search value...",
        "pleaseWait":"Please wait for a moment!",
        "deleteData":"Delete data?",
        "name": "Name",
        "yes":"Yes",
        "no":"No",
        "copy":"Copy",
        "table":"Table",
        "basicTable":"Basic table",
        "selectTable":"Select a table",
        "applications":"Applications",
        "additions":"Additions",
        "logistics":"Logistics",
        "letter":"The letter",
        "fileDirectory":"File directory",
        "admin":"Admin",
        "systemAdministrator":"System administrator",
        "personalInformation":"Personal information",
        "settings":"Settings",
        "logOut":"Log out",
        "changePassword":"Change password ",
        "projectList":"Project list",
        "table_list":"table list",
        "ui_builder":"UI builder",
        "_form":"Form",
        "someContents":"Some contents",
    },

    appAdmin:{},
    chart:{},
    dataForm:{
        "save":"Save",
        "pleaseWait":"Please wait for a moment!",
        "fillInTheNewOne": "Fill in the new one",
        "close":"Close",
        "basicSettings":"Basic settings",
        "configureTheData":"Configure the data",
        "trigger":"Trigger",
        "informationLink":"Information link",
        "GetValuesFromTheTable":"Get values from the table",
        "Geographic":"Geographic",
        "AdditionalValues":"Additional values",
        "selectMultipleImg":"Whether to select multiple images",
        "TypeOfTheEditor":"Type of the editor",
        "Placeholder":"Орлуулагч",
        "default_Value":"Default value",
        "Get_value_parameter":"Get the value from the parameter",
        "Parameter_name":"Name of the parameter",
        "Get_user_ID":"Get a user ID",
        "Consolidation_formula":"Consolidation formula",
    },
    dataGrid:{},
    dataSource:{
        "database": "Database",
        "add": "Add",
        "view": "View",
        "pleaseEnterSearchValue": "Please enter a search value...",
        "pleaseWait":"Please wait for a moment!",
        "deleteData":"Delete data?",
        "yes":"Yes",
        "no":"No",
        "dataProcessing": "Data processing",
        "characteristics": "Characteristics",
        "basic": "Basic",
        "column": "Column",
        "name": "Name",
        "additional": "Additional",
        "filter": "Filter",
        "data": "Data",
        "save": "Save",
        "tableList": "List of tables",
        "viewList": "View list",
        "aggregation": "Aggeration",
        "sort": "Sort",
        "noSort": "Do not sort",
        "use": "Use",
        "grouping": "Grouping",
        "type": "Type",
        "alias": "Alias",
        "select": "Select",
        "bolomjitTableAndView":"Available 'table' and 'view'",
        "selectTable":"Select a table",
        "applications":"Applications",
    },
    role:{
        "administraationRightsManagment": "Administration rights management",
        "welcome":"Welcome!",
        "loggedIn":" Logged in",
        "personalInfo":"Personal information",
        "changePass":"Change password",
        "superAdminManagement":"Super admin management",
        "logout":"Log out",
        "pleaseWait":"Please wait for a moment!",
        "add": "Add",
        "pleaseSelectRole": "Please select role?",
        "role":"Role",
        "additional": "Additional",
        "dataSource": "Мэдээллийн эх Data source",
        "userList": "User list",
        "import": "Import",
        "register": "Register",
        "confirm": "Confirm",
        "save": "Save",
        "menuSelection": "Menu selection",
        "possibleTableView": 'Possible "table" and "view"',
        "table": "Table",
        "name": "Name",
        "displayName": "Display name",
        "note":"Note",
        "cancel":"Cancel",
        "defaultMenu":"Default menu",
        "chart":"Chart",
        "tableName":"table name",
    },
    project:{
        "project": "PROJECT",
        "settings":"Settings",
        "data_recording_environment":"DATA RECORDING ENVIRONMENT",
        "_form": "Form",
        "table": "Table",
        "form_and_table_consolidation": "Form and table consolidation",
        "data_processor": "DATA PROCESSOR",
        "_chart": "Chart",
        "original_preparation": "Original preparation",
        "analysis": "Analysis",
        "target_statement": "Target statement",
        "graphql_management": "Graphql management",
        "menu": "MENU",
        "menu_settings":"Menu settings",
        "data_settings": "Data settings",
        "project_key": "Project key",
        "server_languege_framework": "Server language and framework",
        "create_using": "create using",
        "download_create_file": "Download and create a file",
        "lambda": "Lambda",
        "lambda_cli": "Lambda CLI",
        "lambda_example_app": "Lambda example app",
        "l_key": "key",
        "create": "create",
        "lambda_settings": "Lambda settings",
        "laravel_framework": "PHP: Laravel framework",
        "go_framework": "Go: Echo framework",
        "database": "Database",
        "database_connect": "Database connection",
        "ready": "Ready",
        "_success": "I wish you success",
        "type": "type",
        "manage_access_rights":"Manage access rights",
        "please_wait":"Please wait for a moment",
        "add":"Add",
        "menuSelection": "Menu selection",
        "default_menu": "Default menu",
        "lambda_platform": "composer create-project lambda-platform/laravel",
        "composer": "Composer",
        "_save": "Save",
        "optional":"Optional",
        "data_source": "Data source",
        "_moqup": "Moqup",
        "user_list": "User list",
        "_import": "Import",
        "register": "Register",
        "_confirm": "Confirm",
    },
    puzzle:{
        "manage_access_rights":"Manage access rights",
        "data_recording_environment":"DATA RECORDING ENVIRONMENT",
        "_form": "Form",
        "table": "Table",
        "form_and_table_consolidation": "Form and table consolidation",
        "data_processor": "DATA PROCESSOR",
        "data_settings": "Data settings",
        "_chart": "Chart",
        "original_preparation": "Original preparation",
        "_report": "Report",
        "analysis": "Analysis",
        "target_statement": "Target statement",
        "graphql_management": "Graphql management",
        "usersAndUserGroups":"User, User group",
        "users":"Users",
        "userGroupsPermission":"User groups, Permissions",
        "menu_settings":"Menu settings",
        "logOut": "Log out",
        "cancel":"Cancel",
        "please_wait":"Please wait for a moment",
        "add":"Add",
        "_save":"Save",
        "optional":"Optional",
        "duties":"Duties",
        "_name": "Name",
        "appearance_name": "Appearance name",
        "note": "Note",
        "please_select_role": "Please select a role",
        "data_source": "Data source",
        "_moqup": "Moqup",
        "user_list": "User list",
        "_import": "Import",
        "default_menu": "Default menu",
        "register": "Register",
        "_confirm": "Confirm",
        "list_grid": "List | Grid",
        "custom_column": "Custom column",
        "judgment_column": "Judgment column",
        "value_column": "Value column",
        "delete_data": "Please delete the data",
        "menuSelection": "Menu selection",
        "not_found": "not found",
        "meaningTake": "Meaning to take",
        "filter": "filter",
    },
    notify:{
        "notice": "Notices",
        "no_notice": "No announcements yet!",
        "view_all_notifications": "View all notifications",
    },
    moqup:{
        "elements":"elements",
        "chart":"Chart",
        "save": "save",
        "embedlink": "Embed link",
        "edit":"Edit",
    },
    page:{
        "pageNotFound":"The Page can't be found",
    },
}
