export default {
    locale: 'en-us',
    user:{
        "title": "Lambda Platform",
        "subtitle": "Lambda Platform",
        "login": "Login",
        "forgot": "Forgot password?",
        "remember": "Remember me",
        "loginTitle": "Login to system",
        "username": "Username",
        "email": "e-mail",
        "password": "Password",
        "loginSuccess": "Successfully logged in. Please wait for a moment!",
        "loginError": "Sorry, an error occurred while logging in!!",
        "emailRequired": "Please enter an email address",
        "emailSendError": "An error occurred while sending the email",
        "forgotDescription": "Enter your email address and reset your password",
        "sendPasswordResetCode": "Receive password reset code by email",
        "passwordConfirm": "Password verification",
        "userNotFound": "User not found !!!",
        "codeSentError": "An error occurred while sending the password update code!",
        "passwordReset": "Password reset",
        "passwordResetCode": "Password reset code",
        "passwordResetCodeSent": "Password update code sent successfully !",
        "passwordResetCodeRequired": "Password change code not included !!!",
        "passwordResetSuccess": "Password successfully updated !",
        "passwordConfirmError": "Password authentication did not match !!!",
        "passwordResetCodeIncorrect": "The password recovery code is incorrect !!!",
        "passwordResetCodeTimeout": "Password recovery code has expired !!!",
        "noReply": "This email was sent automatically, so there is no need to reply.",
        "databaseview": "Database, view",
        "dataBase": "database",
        "view": "VIEW",
        "add": "add",
        "characteristics": "Characteristics",
        "basic": "Basic",
        "column": "column",
        "name": "name",
        "optional": "optional",
        "filter": "filter",
        "data": "data",
        "save": "save",
        "tableList"	: "table list",
        "aggregation": "Aggregation",
        "sort": "sort",
        "use": "use",
        "grouping": "grouping",
        "type": "type",
        "alias": "alias",
        "dataProcessing": "Data processing",
        "select": "select",
        "pleaseEnterSearchValue": "Please enter a search value",
        "user": "User",
        "users": "Users",
        "totalEmployees": "Total employees",
        "deleted": "Deleted",
        "searchForInformation": "Search for information",
        "addUser": "Add a user",
        "noData": "No matching data",
        "page": "page",
        "shows": "shows",
        "categorySearch": "category search",
        "image": "image",
        "lastName": "last name",
        "firstName": "first name",
        "registrationNumber": "Registration number",
        "dateOfBirth": "Date of birth",
        "gender": "gender",
        "men": "Men",
        "women": "Women",
        "phone": "phone",
        "fillInTheNewOne": "Fill in the new one",
        "permission": "Permission",
        "loginName": "Login name",
        "confirmPassword": "Confirm password",
        "personalInformation": "Personal information",
        "changePassword": "Change password",
        "settings": "Settings",
        "logOut": "Log out",
        "pleaseSelectRole": "Please select a role",
        "administraationRightsManagment": "Administration rights management",
        "additional": "ADDITIONAL",
        "dataSource": "Data source",
        "chart": "Chart",
        "userList": "User list",
        "import": "Import",
        "register": "Register",
        "confirm": "Confirm",
        "menuSelection": "Menu selection",
        "noMatchingData": "No matching data",
        "nickName": "Nickname",
        "note": "Note",
        "pleaseEnterVisibleName": "Please enter a visible name",
        "firstNameandLastName": "First name & last name",
        "mobile": "Mobile",
        "createdDate": "created date",
        "registrationConfirmed": "REGISTRATION CONFIRMED",
        "registrationIsNotConfirmed": "REGISTRATION IS NOT CONFIRMED",
        "success": "success",
        "systemUpdate": "System update",
        "sendDataStructure": "Send data structure",
        "pleaseReEnterYourPassword": "Please re-enter your password",
        "theValueIsRegistered": "The value is registered",
        "possibleTableView": 'Possible "table" and "view"',
        "table": "Table",

        "ascending": "Ascending",
        "descending": "descending",
        "dateAdded": "Date added",
        "inPage": "in page",
        "show": "Show",
        "outOf": "total",
        "fromUsers": "from users",
        "showing": "showing",

        logout:"Logout",
        cancel:"Cancel",
    },
    adminModule:{
        db:"Database",
        usersAndUserGroups:"User, User group",
        users:"Users",
        userGroupsPermission:"User groups, Permissions",

        manage_access_rights:"Manage access rights",
    },

    appAdmin:{},
    chart:{},
    dataForm:{},
    dataGrid:{},
    dataSource:{
        "database": "Database",
        "add": "Add",
        "view": "View",
        "pleaseEnterSearchValue": "Please enter a search value",
        "dataProcessing": "Data processing",
        "characteristics": "Characteristics",
        "basic": "Basic",
        "column": "Column",
        "name": "Name",
        "additional": "Additional",
        "filter": "Filter",
        "data": "Data",
        "save": "Save",
        "tableList": "table list",
        "aggregation": "Aggeration",
        "sort": "Sort",
        "use": "Use",
        "grouping": "Grouping",
        "type": "Type",
        "alias": "Alias",
        "select": "Select",
    },
    role:{
        "administraationRightsManagment": "Administration rights management",
        "add": "Add",
        "pleaseSelectRole": "Please select role",
        "additional": "Additional",
        "dataSource": "Мэдээллийн эх Data source",
        "userList": "User list",
        "import": "Import",
        "register": "Register",
        "confirm": "Confirm",
        "save": "Save",
        "menuSelection": "Menu selection",
        "possibleTableView": 'Possible "table" and "view"',
        "table": "Table",
    },
    project:{

    },

}
