export default {
    locale: 'ko-kr',
    agent:{
        "title": "람다 플랫폼",
        "subtitle": "람다 플랫폼",
        "login": "로그인",
        "forgot": "비밀번호 재설정",
        "remember": "계정 저장",
        "loginTitle": "시스템 로그인",
        "username": "ID",
        "email": "이메일",
        "password": "비밀번호",
        "loginSuccess": "로그인 되었습니다. 잠시만 기다려주세요!",
        "loginError": "죄송합니다. 오류가 발생하였습니다. 다시 시도해주세요!",
        "emailRequired": "이메일을 입력하세요.",
        "emailSendError": "이메일을 보내는 동안 오류가 발생했습니다",
        "forgotDescription": "이메일 입력 후 비밀번호를 재설정해주세요.",
        "sendPasswordResetCode": "비밀번호 재설정 코드 이메일로 받기",
        "passwordConfirm": "비밀번호 확인",
        "userNotFound": "회원 정보가 없습니다. 다시 확인해주세요!",
        "codeSentError": "확인 코드 전송 시 오류가 발생하였습니다. 다시 시도해주세요!",
        "passwordReset": "비밀번호 재설정",
        "passwordResetCode": "비밀번호 재설정 코드",
        "passwordResetCodeSent": "확인 코드가 전송되었습니다.",
        "passwordResetCodeRequired": "확인 코드가 입력하지 않았습니다!",
        "passwordResetSuccess": "비밀번호가 정상적으로 변경되었습니다!",
        "passwordConfirmError": "비밀번호가 일치하지 않습니다!",
        "passwordResetCodeIncorrect": "확인 코드가 맞지 않습니다. 다시 확인해주세요!",
        "passwordResetCodeTimeout": "시간이 초과되었습니다. 다시 시도해주세요!",
        "noReply": "본 메일은 발신전용입니다..",
        "database": "데이터 베이스",
        "view": "보다",
        "add": "추가하다",
        "characteristics": "형질",
        "basic": "기초적인",
        "column": "열",
        "name": "이름",
        "optional": "선택 과목",
        "filter": "필터",
        "data": "데이터",
        "save": "저장",
        "tableList": "테이블 목록",
        "aggregation": "집합",
        "sort": "종류",
        "use": "사용하다",
        "grouping": "그룹화",
        "type": "유형",
        "alias": "별명",
        "dataProcessing": "데이터 처리",
        "select": "선택하다",
        "pleaseEnterSearchValue": "검색 값을 입력하십시오",
        "user": "사용자",
        "users": "사용자",
        "totalEmployees": "총 직원",
        "deleted": "삭제됨",
        "searchForInformation": "정보 검색",
        "addUser": "사용자 추가",
        "noData": "데이터 없음",
        "page": "페이지",
        "shows": "쇼",
        "categorySearch": "카테고리 검색",
        "image": "영상",
        "lastName": "성",
        "firstName": "이름",
        "registrationNumber": "등록 번호",
        "dateOfBirth": "생일",
        "gender": "성별",
        "men": "남자들",
        "women": "여성",
        "phone": "핸드폰",
        "fillInTheNewOne": "새로운 것을 채우십시오",
        "permission": "허가",
        "loginName": "로그인 이름",
        "confirmPassword": "비밀번호 확인",
        "personalInformation": "개인 정보",
        "changePassword": "비밀번호 변경",
        "settings": "설정",
        "logOut": "로그 아웃",
        "pleaseSelectRole": "역할을 선택하세요.",
        "administraationRightsManagment": "행정권 관리",
        "additional": "추가의",
        "dataSource": "데이터 소스",
        "chart": "차트",
        "userList": "사용자 목록",
        "import": "수입",
        "register": "등록하다",
        "confirm": "확인하다",
        "menuSelection": "메뉴 선택",
        "noMatchingData": "일치하는 데이터가 없습니다",
        "nickName": "별명",
        "note": "메모",
        "pleaseEnterVisibleName": "보이는 이름을 입력하세요",
        "firstNameandLastName": "이름 및 성",
        "mobile": "이동하는",
        "createdDate": "만든 날짜",
        "registrationConfirmed": "등록 확인됨",
        "registrationIsNotConfirmed": "등록이 확인되지 않았습니다",
        "success": "성공적인",
        "systemUpdate": "시스템 업데이트",
        "sendDataStructure": "데이터 구조 보내기",
        "pleaseReEnterYourPassword": "비밀번호를 다시 입력하세요",
        "theValueIsRegistered": "값이 등록되었습니다",
        "possibleTableView": '가능한 "테이블" 및 "보기"',
        "table": "테이블",
        "ascending": "오름차순",
        "descending": "내림차순",
        "byLoginName": "로그인 이름으로",
        "dateAdded": "추가된 날짜",
        "inPage": "인페이지",
        "show": "보여 주다",
        "outOf": "총",
        "fromUsers": "사용자로부터",
        "showing": "전시",
        "noInfo":"정보 없음 ",
        "ruconfinfo": "직원 정보 검색에 자신이 있습니까?",
        "ruconfinfoDelete": "직원 정보를 완전히 삭제하시겠습니까?",
        "created": "만들어진",
        "userDeleted": "사용자가 삭제됨",
        "_logout":"출구",
        "_cancel":"취소",
        "listOfDeletedUsers": "삭제된 사용자 목록",
        "by": " ~에 의해",
        "no":"아니요",
        "yes":"예",
        "completeDestruction": "전파",
        "recovery": "회복",
        "errorOccWhileDeleting": "삭제하는 동안 오류가 발생했습니다",
        "userInformationRestored": "사용자 정보 복원",
        "errorOccurredWhileRetrievingData": "데이터를 검색하는 동안 오류가 발생했습니다",

    },
    adminModule:{
        "db": "데이터베이스",
        "usersAndUserGroups": "소비자 권리",
        "users": "사용자",
        "userGroupsPermission": "액세스 권한, 권한",
        "sendDBSchema":"데이터베이스 스키마 보내기",
        "applications":"애플리케이션",
        "additions":"추가 사항",
        "logistics":"물류 센터",
        "AddColumn":"열 추가",
        "systemUpdate":"시스템 업데이트",
        "graphic":"그래픽",
        "column":"열",
        "dataType":"데이터 형식",
        "form":"형태",
        "table":"테이블",
        "original_preparation": "원래 준비",
    },
    graphql:{
        "graphqlManagement":"Graphql 관리",
        "table":"테이블",
        "selectTable":"테이블 선택",
        "name": "이름",
        "idField":" ID 필드",
        "hideFields":"필드 숨기기",
        "permissionActions":"권한 작업",
        "add":"추가하다",
        "edit":"편집하다",
        "delete":"삭제",
        "save": "저장",
        "accessAndAccessRights":"접근 및 접근 권한",
        "nevtersenHundHaruulah":"로그인 한 모든 사람에게 보여줍니다.",
        "accessRights":"액세스 권한",
        "allUsersCanSee":"권한이 없는 경우 모든 사용자가 볼 수 있습니다.",
        "subTables":"하위 테이블",
        "subTable":"하위 테이블",
        "connectionField":"연결 필드",
    },
    components:{
        "add": "추가하다",
        "pleaseEnterSearchValue": "검색 값을 입력하십시오...",
        "pleaseWait":"잠시만 기다려주세요!",
        "deleteData":"데이터를 삭제하시겠습니까?",
        "name": "이름",
        "yes":"예",
        "no":"아니요",
        "copy":"복사",
        "table":"테이블",
        "basicTable":" 기본 테이블",
        "selectTable":"테이블 선택",
        "applications":"애플리케이션",
        "additions":"추가 사항",
        "logistics":"물류 센터",
        "letter":"그 편지",
        "fileDirectory":"파일 디렉토리",
        "admin":"관리자",
        "systemAdministrator":"시스템 관리자",
        "personalInformation":"개인 정보",
        "settings":"설정",
        "logOut":"로그 아웃",
        "changePassword":"비밀번호 변경",
        "projectList":"프로젝트 목록",
        "table_list":"테이블 목록",
        "ui_builder":"UI 빌더",
        "_form":"형태",
    },

    appAdmin:{},
    chart:{},
    dataForm:{},
    dataGrid:{},
    dataSource:{
        "database": "데이터 베이스",
        "add": "추가하다",
        "view": "보다",
        "pleaseEnterSearchValue": "검색 값을 입력하십시오...",
        "pleaseWait":"잠시만 기다려주세요!",
        "deleteData":"데이터를 삭제하시겠습니까?",
        "yes":"예",
        "no":"아니요",
        "dataProcessing": "데이터 처리",
        "characteristics": "형질",
        "basic": "기초적인",
        "column": "열",
        "name": "이름",
        "additional": "추가의",
        "filter": "필터",
        "data": "데이터",
        "save": "저장",
        "tableList": "테이블 목록",
        "viewList": "View 목록",
        "aggregation": "집합",
        "sort": "종류",
        "noSort": "정렬하지 않음",
        "use": "사용하다",
        "grouping": "그룹화",
        "type": "유형",
        "alias": "별명",
        "select": "선택하다",
        "bolomjitTableAndView":"사용 가능한 'table' 및 'view'",
    },
    role:{
        "administraationRightsManagment": "행정권 관리",
        "welcome":"어서 오십시오!",
        "loggedIn":"로그인",
        "personalInfo":"개인 정보",
        "changePass":"비밀번호 변경",
        "superAdminManagement":"최고 관리자 관리",
        "logout":"로그 아웃",
        "pleaseWait":"잠시만 기다려주세요!",
        "add": "추가하다",
        "pleaseSelectRole": "역할을 선택하세요?",
        "role":"직장",
        "additional": "추가의",
        "dataSource": "데이터 소스",
        "userList": "사용자 목록",
        "import": "수입",
        "register": "등록하다",
        "confirm": "확인하다",
        "save": "저장",
        "menuSelection": "메뉴 선택",
        "possibleTableView": '가능한 "테이블" 및 "보기"',
        "table": "테이블",
        "name": "이름",
        "displayName": "외모 이름",
        "note":"말",
        "cancel":"취소",
        "defaultMenu":"기본 메뉴",
        "chart":"차트",
    },
    project:{

    },
    puzzle:{
        "manage_access_rights":"접근 권한 관리",
        "data_recording_environment":"데이터 기록 환경",
        "_form": "형태",
        "table": "테이블",
        "form_and_table_consolidation": "양식 및 스프레드시트",
        "data_processor": "데이터 프로세서",
        "data_settings": "데이터 설정",
        "_chart": "차트",
        "original_preparation": "원래 준비",
        "_report": "보고서",
        "analysis": "분석",
        "target_statement": "목표문",
        "graphql_management": "Graphql 관리",
        "usersAndUserGroups": "소비자 권리",
        "users": "사용자",
        "userGroupsPermission": "액세스 권한, 권한",
        "menu_settings":"메뉴 설정",
        "logOut": "로그 아웃",
        "cancel":"취소",
        "please_wait":"잠시만 기다려주세요",
        "add":"추가하다",
        "_save":"구하다",
        "optional":"선택 과목",
        "duties":"직장",
        "_name": "이름",
        "appearance_name": "외모 이름",
        "note": "메모",
        "please_select_role": "역할을 선택하세요.",
        "data_source": "데이터 소스",
        "_moqup": "모쿱",
        "user_list": "용자 목록",
        "_import": "수입",
        "default_menu": "기본 메뉴",
        "register": "등록하다",
        "_confirm": "확인하다",
        "list_grid": "목록 | 그리드",
        "custom_column": "맞춤 열",
        "judgment_column": "판정란",
        "value_column": "값 열",
        "delete_data": "데이터를 삭제해주세요",
        "menuSelection": "메뉴 선택",
        "not_found": "찾을 수 없음",
    }
}
