export default {
    locale: 'ko-kr',
    agent:{
        "title": "람다 플랫폼",
        "subtitle": "람다 플랫폼",
        "login": "로그인",
        "forgot": "비밀번호 재설정",
        "remember": "계정 저장",
        "loginTitle": "시스템 로그인",
        "username": "ID",
        "email": "이메일",
        "password": "비밀번호",
        "loginSuccess": "로그인 되었습니다. 잠시만 기다려주세요!",
        "loginError": "죄송합니다. 오류가 발생하였습니다. 다시 시도해주세요!",
        "emailRequired": "이메일을 입력하세요.",
        "emailSendError": "이메일을 보내는 동안 오류가 발생했습니다",
        "forgotDescription": "이메일 입력 후 비밀번호를 재설정해주세요.",
        "sendPasswordResetCode": "비밀번호 재설정 코드 이메일로 받기",
        "passwordConfirm": "비밀번호 확인",
        "userNotFound": "회원 정보가 없습니다. 다시 확인해주세요!",
        "codeSentError": "확인 코드 전송 시 오류가 발생하였습니다. 다시 시도해주세요!",
        "passwordReset": "비밀번호 재설정",
        "passwordResetCode": "비밀번호 재설정 코드",
        "passwordResetCodeSent": "확인 코드가 전송되었습니다.",
        "passwordResetCodeRequired": "확인 코드가 입력하지 않았습니다!",
        "passwordResetSuccess": "비밀번호가 정상적으로 변경되었습니다!",
        "passwordConfirmError": "비밀번호가 일치하지 않습니다!",
        "passwordResetCodeIncorrect": "확인 코드가 맞지 않습니다. 다시 확인해주세요!",
        "passwordResetCodeTimeout": "시간이 초과되었습니다. 다시 시도해주세요!",
        "noReply": "본 메일은 발신전용입니다.."
    },
    puzzle:{
        db: "데이터베이스",
        usersAndUserGroups: "소비자 권리",
        users: "사용자",
        userGroupsPermission: "액세스 권한, 권한",
        manage_access_rights:"접근 권한 관리",
    },
    common:{
        logout:"출구",
    }
}
