export default {
    locale: 'mn-mn',
    user:{
        "view": "харах",
        "add": "Нэмэх",
        "user": "хэрэглэгч",
        "permission": "Хандах эрх",
        "users": "Хэрэглэгчид",
        "totalEmployees": "Нийт ажилчид",
        "deleted": "Устгасан",
        "searchForInformation": "Мэдээллээс хайх",
        "addUser": "Хэрэглэгч нэмэх",
        "noData": "Мэдээлэл олдсонгүй",
        "page": "Хуудсанд",
        "shows": "харуулана",
        "categorySearch": "Зэрэглэлээр шүүх",
        "image": "Зураг",
        "lastName": "Овог",
        "firstName": "Нэр",
        "registrationNumber": "Регистрийн дугаар",
        "dateOfBirth": "Төрсөн огноо",
        "gender": "Хүйс",
        "men": "Эрэгтэй",
        "women": "Эмэгтэй",
        "phone": "Утас",
        "fillInTheNewOne": "Шинээр бөглөх",
        "loginName": "Нэвтрэх нэр",
        "confirmPassword": "Нууц үг баталгаажуулах",
        "personalInformation": "Хувийн мэдээлэл",
        "changePassword": "Нууц үг солих",
        "settings": "Тохиргоо",
        "logOut": "Системээс гарах",
        "pleaseSelectRole": "Үүрэг сонгоно уу",
        "administraationRightsManagment": "ХАНДАХ ЭРХ УДИРДАХ",
        "dataSource": "Мэдээллийн эх сурвалж",
        "chart": "График",
        "register": "Бүртгэх",
        "confirm": "Баталгаажуулах",
        "menuSelection": "Цэс сонгох",
        "noMatchingData": "Тохирох өгөгдөл байхгүй байна",
        "nickName": "Харагдах нэр",
        "note": "Тайлбар",
        "pleaseEnterVisibleName": "Харагдах нэрийг оруулна уу",
        "firstNameandLastName": "Овог нэр",
        "mobile": "Гар утас",
        "createdDate": "Үүсгэсэн огноо",
        "registrationConfirmed": "БҮРТГЭЛ БАТАЛГААЖСАН",
        "registrationIsNotConfirmed": "БҮРТГЭЛ БАТАЛГААЖААГҮЙ",
        "success": "Амжилттай",
        "systemUpdate": "Систем шинэчлэх",
        "sendDataStructure": "Өгөгдлийн бүтцийг илгээх",
        "pleaseReEnterYourPassword": "Нууц үгээ дахин оруулна уу",
        "theValueIsRegistered": "утга бүртгэлтэй байна",
        "title": "Lambda Platform",
        "subtitle": "Lambda Platform",
        "login": "Нэвтрэх",
        "forgot": "Нууц үгээ мартсан?",
        "remember": "Энэ компьютерт сануулах",
        "loginTitle": "СИСТЕМД НЭВТРЭХ",
        "username": "Нэвтрэх нэр",
        "email": "И-мэйл",
        "password": "Нууц үг",
        "loginSuccess": "Амжилттай нэвтэрлээ. Түр хүлээнэ үү!",
        "loginError": "Уучлаарай, нэвтрэх үед алдаа гарлаа!!",
        "emailRequired": "И-мэйл хаяг аа оруулна уу",
        "emailSendError": "И-мэйл илгээх үед алдаа гарлаа",
        "forgotDescription": "И-мэйл хаягаа оруулаад нууц үг ээ сэргээнэ үү",
        "sendPasswordResetCode": "Нууц үг солих код и-мэйлээр авах",
        "passwordConfirm": "Нууц үг баталгаажуулах",
        "userNotFound": "Хэрэглэгч олдсонгүй !!!",
        "codeSentError": "Нууц үг шинэчлэх код илгээх үед алдаа гарлаа!",
        "passwordReset": "НУУЦ ҮГ ШИНЭЧЛЭХ",
        "passwordResetCode": "Нууц үгээ сэргээх код",
        "passwordResetCodeSent": "Нууц үг шинэчлэх код амжилттай илгээгдлээ !",
        "passwordResetCodeRequired": "Нууц үг солих код  оруулаагүй байна !!!",
        "passwordResetSuccess": "Нууц үг амжилттай шинэчлэгдлээ !",
        "passwordConfirmError": "Нууц үг баталгаажуулалт таарсангүй !!!",
        "passwordResetCodeIncorrect": "Нууц үг сэргээх код буруу байна !!!",
        "passwordResetCodeTimeout": "Нууц үг сэргээх кодын хугацаа дууссан !!!",
        "noReply": "Энэхүү и-мэйл нь автоматаар илгээгдсэн учир хариу бичих шаардлагагүй.",
        "userList": "Хэрэглэгчдийн жагсаалт",
        "sort": "Эрэмбэлэх",
        "ascending": "өсөхөөр",
        "descending": "Буурах",
        "byLoginName": "Нэвтрэх нэрээр",
        "dateAdded": "Нэмсэн огноо",
        "inPage": "Хуудсанд",
        "show": "харуулана",
        "outOf": "Нийт",
        "fromUsers": "хэрэглэгчдээс",
        "showing": "харуулж байна",
        "noInfo":"Мэдээлэл алга ",
        "ruconfinfo": "Ажилтны мэдээллийг сэргээхдээ итгэлтэй байна уу?",
        "ruconfinfoDelete": "Ажилтны мэдээллийг бүр мөсөн устгахдаа итгэлтэй байна уу?",
        "created": "Үүсгэсэн",
        "userDeleted": "Хэрэглэгч устгагдлаа",
        "listOfDeletedUsers": "Устгасан хэрэглэгчдийн жагсаалт",
        "logout":"Гарах",
        "cancel":"Болих",
        "by": " - аар",
        "no":"Үгүй",
        "yes":"Тийм",
        "completeDestruction": "Бүр мөсөн устгах",
        "recovery": "Сэргээх",
        "errorOccWhileDeleting": "Устгах үед алдаа гарлаа",
        "userInformationRestored": "Хэрэглэгчийн мэдээлэл сэргээгдлээ",
        "errorOccurredWhileRetrievingData": "Мэдээлэл сэргээхэд алдаа гарлаа",


    },
    adminModule:{
        "db":"Өгөгдлийн сан",
        "usersAndUserGroups":"ХЭРЭГЛЭГЧ, ХАНДАХ ЭРХ",
        "users":"Хэрэглэгчид",
        "userGroupsPermission":"Хандах эрх, Зөвшөөрөл",
        "sendDBSchema":"Өгөгдлийн сангийн бүтцийг илгээх",
        "database": "Өгөгдлийн сан",
        "AddColumn":"Багана нэмэх",
        "graphqlManagement":"Graphql удирдлага",
        "table":"Хүснэгт",
        "selectTable":"Хүснэгт сонгох",
        "name": "Нэр",
        "idField":"ID талбар",
        "hideFields":"Нуух талбарууд",
        "permissionActions":"Зөвшөөрөх үйлдлүүд",
        "add":"Нэмэх",
        "edit":"Засах",
        "delete":"Устгах",
        "accessAndAccessRights":"Нэвтрэлт болон хандах эрх",
        "nevtersenHundHaruulah":"Нэвтэрсэн хүнд харуулна.",
    },
    components:{
        "add": "Нэмэх",
        "pleaseEnterSearchValue": "Хайх утгаа оруулна уу...",
        "pleaseWait":"Түр хүлээнэ үү!",
        "deleteData":"Өгөгдөлийг устгах уу?",
        "name": "Нэр",
        "yes":"Тийм",
        "no":"Үгүй",
        "copy":"Хувилах",
        "table":"Хүснэгт",
        "basicTable":"Үндсэн хүснэгт",
        "selectTable":"Хүснэгт сонгох",
        "applications":"Програмууд",
        "additions":"Нэмэлтүүд",
        "logistics":"Ложистик",
        "letter":"Захидал",
        "fileDirectory":"Файлын сан",
        "admin":"Админ",
        "systemAdministrator":"Системийн админ",
        "personalInformation":"Хувийн мэдээлэл",
        "settings":"Тохиргоо",
        "logOut":"Системээс гарах",
        "changePassword":"Нууц үг солих ",
        "projectList":"Төслийн жагсаалт",

    },

    appAdmin:{},
    chart:{},
    dataForm:{},
    dataGrid:{},
    dataSource:{
        "database": "Өгөгдлийн сан ",
        "add": "Нэмэх",
        "view": "харах",
        "pleaseEnterSearchValue": "Хайх утгаа оруулна уу...",
        "pleaseWait":"Түр хүлээнэ үү!",
        "yes":"Тийм",
        "no":"Үгүй",
        "deleteData":"Өгөгдөлийг устгах уу?",
        "dataProcessing": "Өгөгдөл боловсруулах",
        "characteristics": "Шинж чанар",
        "basic": "Үндсэн",
        "column": "Багана",
        "name": "Нэр",
        "additional": "Нэмэлт",
        "filter": "Шүүлтүүр",
        "data": "Өгөгдөл",
        "save": "Хадгалах",
        "tableList": "Хүснэгтийн жагсаалт",
        "viewList": "View жагсаалт",
        "aggregation": "Нэгтгэх",
        "sort": "Эрэмбэлэх",
        "noSort": "Эрэмблэхгүй",
        "use": "Хэрэглэх",
        "grouping": "Бүлэглэх",
        "type": "Төрөл",
        "alias": "Зохиомол нэр",
        "select": "Сонгох",
        "bolomjitTableAndView":"Боломжит 'table' болон 'view'",

    },
    role:{
        "administraationRightsManagment": "ХАНДАХ ЭРХ УДИРДАХ",
        "welcome":"Тавтай морил!",
        "loggedIn":"Нэвтэрсэн хэрэглэгч",
        "personalInfo":"Хувийн мэдээлэл",
        "changePass":"Нууц үг солих",
        "superAdminManagement":"Сүпер админ удирдлага",
        "logout":"Системээс гарах",
        "pleaseWait":"Түр хүлээнэ үү!",
        "add": "Нэмэх",
        "pleaseSelectRole": "Үүрэг сонгоно уу?",
        "role":"Үүрэг",
        "additional": "Нэмэлт",
        "dataSource": "Мэдээллийн эх сурвалж",
        "userList": "Хэрэглэгчдийн жагсаалт",
        "import": "Импорт хийх",
        "register": "Бүртгэх",
        "confirm": "Баталгаажуулах",
        "save": "Хадгалах",
        "menuSelection": "Цэс сонгох",
        "possibleTableView": 'Боломжиж "table" болон "view"',
        "table": "Хүснэгт",
        "name": "Нэр",
        "displayName": "Харагдах нэр",
        "note":"Тайлбар",
        "cancel":"Болих",
    },
    project:{

    },
    puzzle:{
        "manage_access_rights":"Хандах эрх удирдах",
        "data_recording_environment":"ӨГӨГДӨЛ БҮРТГЭХ ОРЧИН ҮҮСГЭГЧ",
        "form": "Маягт",
        "table": "Хүснэгт",
        "form_and_table_consolidation": "Маягт, хүснэгт нэгтгэл",
        "data_processor": "МЭДЭЭЛЭЛ БОЛОВСРУУЛАГЧ",
        "data_settings": "Өгөгдлийн тохиргоо",
        "chart": "График",
        "original_preparation": "Эх бэлтгэл",
        "report": "Тайлан",
        "analysis": "Анализ",
        "target_statement": "Зорилтод мэдэгдэл",
        "graphql_management": "Graphql удирдлага",
        "usersAndUserGroups":"ХЭРЭГЛЭГЧ, ХАНДАХ ЭРХ",
        "users": "Хэрэглэгчид",
        "userGroupsPermission":"Хандах эрх, Зөвшөөрөл",
        "menu_settings":"Цэсний тохиргоо",
        "logOut":"Гарах",
        "cancel":"Болих",
        "please_wait":"Түр хүлээнэ үү",
        "add":"Нэмэх",
        "_save":"Хадгалах",
        "optional":"Нэмэлт",
        "duties":"Үүрэг",
        "name": "Нэр",
        "appearance_name": "Харагдах нэр",
        "note": "Тайлбар",
        "please_select_role": "Үүрэг сонгоно уу",
        "data_source": "Мэдээллийн эх сурвалж",
        "moqup": "Мокуп",
        "user_list": "Хэрэглэгчийн жагсаалт",
        "import": "Импорт хийх",
        "register": "Бүртгэх",
        "_confirm": "Баталгаажуулах",
        "list_grid": "Жагсаалт | Grid (шүүлтүүр)",
        "custom_column": "Хэрэглэгчийн багана",
        "judgment_column": "Хэрэглэгчийн багана",
        "value_column": "Утга багана",
        "delete_data": "Өгөгдөлийг устгах уу",
    }

}
